export const apartments = [
    {
        id: 1,
        category: "service apartment",
        subCategory: "Studio",
        title: "Furnished Studio Apartment on the Upper East Side, NYC",
        features: "This charming, stylishly designed studio is located in a newly refurbished, turn-of-the-century townhouse on a beautiful residential block on Manhattan's coveted Upper East Side, within walking distance to Central Park and the Metropolitan Museum of Art. The studio features a kitchenette, hardwood floors, and complimentary WiFi. Building amenities include an on-site building manager, keyless entry and intercom system for added security and on-site laundry facilities. The building is a walk-up and does not have an elevator.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Cleaning service •• etc..",
        oldPrice: "$135",
        newPrice: "$120",
        night: "$120",
        week: "$780",
        month: "$3,500",
        street: "248 East 74th Street",
        city: "New York",
        country: "United States",
        rating: "4",
        rated: "(37)",
        popular: true,
        images: ["../img/id1-1.jpg", "../img/id1-2.jpg", "../img/id1-3.jpg", "../img/id1-4.jpg", "../img/id1-5.jpg", "../img/id1-6.jpg"]
    },
    {
        id: 2,
        category: "service apartment",
        subCategory: "Studio",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 3,
        category: "for sale",
        subCategory: "4 bedroom",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 4,
        category: "for sale",
        subCategory: "Mansion",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 5,
        category: "for rent",
        subCategory: "Studio",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 6,
        category: "for sale",
        subCategory: "Studio",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 7,
        category: "for sale",
        subCategory: "5 bedroom",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 8,
        category: "for rent",
        subCategory: "1 bedroom",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 9,
        category: "for rent",
        subCategory: "Mansion",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 10,
        category: "for sale",
        subCategory: "Mansion",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    {
        id: 11,
        category: "for rent",
        subCategory: "Mansion",
        title: "Studio Apartment at Anagram NoMad in The Flatiron District, NYC",
        features: "This sophisticated studio apartment is located in a 50-story high rise above Madison Square Park. The stylish apartment features gorgeous finishes, including stainless steel appliances, granite countertops, hardwood floors and spacious closets. The bed provided is queen size. Building amenities include a full-service concierge, a 24-hour attended lobby, a fitness center, laundry facilities and a wraparound roof deck.",
        amenities: "1 Bathroom •• Smart TV with streaming services •• Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• 24/7 Guest Service •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$210",
        newPrice: "$185",
        night: "$185",
        week: "$1,245",
        month: "$5,450",
        street: "10 East 29th Street",
        city: "New York",
        country: "United States",
        rating: "5",
        rated: "(102)",
        popular: true,
        images: ["../img/id2-1.jpg", "../img/id2-2.jpg", "../img/id2-3.jpg", "../img/id2-4.jpg", "../img/id2-5.jpg", "../img/id2-6.jpg", "../img/id2-7.png", "../img/id2-8.png", "../img/id2-9.png", "../img/id2-10.png", "../img/id2-11.png"]
    },
    
    
    
    
    //features: "Open living room with Sofas •• 3 bedrooms with king size beds •• 3 bath all ensuite •• Dining table for 6 •• Smart TV with streaming services •• etc... ",
];