export const apartments = [
    {
        id: 1,
        category: "la",
        title: "Royal choice luxury apartment",
        oldPrice: "$1700",
        newPrice: "$1550",
        features: "Open living room with Sofas •• 3 bedrooms with king size beds •• 3 bath all ensuite •• Dining table for 6 •• Smart TV with streaming services •• etc... ",
        amenities: "Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$1700",
        newPrice: "$1550",
        night: "$150",
        week: "$900",
        month: "$3,200",
        street: "52 Kingsway",
        city: "San Francisco",
        country: "United States",
        rating: "2",
        rated: "(47)",
        popular: true,
        images: ["../img/property-1.jpg", "../img/property-2.jpg", "../img/property-3.jpg"]
    },
    {
        id: 2,
        category: "2ba",
        title: "AKA Marylone",
        oldPrice: "$1200",
        newPrice: "$1050",
        night: "$150",
        week: "$900",
        month: "$3,200",
        street: "1001 Milverton lane",
        city: "London",
        country: "United Kingdom",
        rating: "4",
        rated: "(103)",
        popular: false,
        images: ["../img/property-4.jpg", "../img/property-5.jpg", "../img/property-6.jpg"]
    },
    {
        id: 3,
        category: "sa",
        title: "Exclusive Living",
        oldPrice: "$2150",
        newPrice: "$2099",
        features: "Open living room with Sofas •• 3 bedrooms with king size beds •• 3 bath all ensuite •• Dining table for 6 •• Smart TV with streaming services •• etc... ",
        amenities: "Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "$1700",
        newPrice: "$1550",
        night: "$150",
        week: "$900",
        month: "$3,200",
        street: "72 love street",
        city: "Paris",
        country: "France",
        rating: "1",
        rated: "(06)",
        popular: false,
        images: ["../img/property-2.jpg", "../img/property-6.jpg", "../img/property-1.jpg"]
    },
    {
        id: 4,
        category: "2ba",
        title: "Kings Haven",
        oldPrice: "$1100",
        newPrice: "$999",
        night: "$150",
        week: "$900",
        month: "$3,200",
        street: "302 Prince Avenue",
        city: "Dubai",
        country: "United Arab Emirates",
        rating: "5",
        rated: "(28)",
        popular: true,
        images: ["../img/property-3.jpg", "../img/property-5.jpg", "../img/property-4.jpg"]
    },
    {
        id: 5,
        category: "la",
        title: "Jumbo jat",
        oldPrice: "$1100",
        newPrice: "$999",
        night: "$150",
        week: "$900",
        month: "$3,200",
        street: "302 Prince Avenue",
        city: "London",
        country: "United Kingdom",
        rating: "5",
        rated: "(28)",
        popular: true,
        images: ["../img/property-3.jpg", "../img/property-5.jpg", "../img/property-4.jpg"]
    },
    {
        id: 6,
        category: "la",
        title: "Exclusive Living",
        oldPrice: "$2150",
        newPrice: "$2099",
        features: "Open living room with Sofas •• 3 bedrooms with king size beds •• 3 bath all ensuite •• Dining table for 6 •• Smart TV with streaming services •• etc... ",
        amenities: "Wi-Fi •• AC & heating •• Fully equipped kitchen •• In-unit washer & dryer •• 24/7 security •• Fitness center •• Cleaning service •• etc..",
        oldPrice: "US$1700",
        newPrice: "$1550",
        night: "$150",
        week: "$900",
        month: "$3,200",
        street: "72 love street",
        city: "New York City",
        country: "United States",
        rating: "3",
        rated: "(926)",
        popular: false,
        images: ["../img/property-2.jpg", "../img/property-6.jpg", "../img/property-1.jpg"]
  }
];